language: cpp

os:
  - osx
compiler:
  - clang

script:
  - export KUL_GIT_CO="--depth 3"
  - git clone https://github.com/Dekken/maiken -b master --depth 1 maiken
  - make bsd CXX=clang++ -C maiken
  - mv maiken/mkn .
  - ./mkn build -dtKa "-O2 -std=c++14" -l "-pthread -ldl" -p test run
