name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: dbg
      run: |
        set -x
        ld -v
        ldd --version
        g++ -v

    - name: upgrade
      run: |
        sudo apt-get update
        sudo apt-get dist-upgrade -y

    - name: dbg
      run: |
        set -x
        ld -v
        ldd --version
        g++ -v

    - name: get
      uses: dawidd6/action-download-artifact@v2
      with:
        name: mkn
        branch: master
        workflow: build_nix.yml
        repo: mkn/maiken

    - name: "mkn"
      run: |
        chmod +x mkn
        KLOG=3 ./mkn clean build run -dtOp test -a "-std=c++17 -fPIC"
