name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get mkn
      uses: dawidd6/action-download-artifact@v2
      with:
        name: mkn
        branch: master
        workflow: build_nix.yml
        repo: mkn/maiken

    - name: "Build/Test"
      run: |
        chmod +x mkn
        ldd mkn
        ls -l /usr/local/lib64
        KLOG=3 ./mkn clean build run -dtOp test -a "-std=c++17 -fPIC"
