name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: get
      uses: dawidd6/action-download-artifact@v2
      with:
        name: mkn
        branch: master
        workflow: build_nix.yml
        repo: mkn/maiken

    - name: dbg
      run: |
        chmod +x mkn
        set -x
        ld -v
        ldd --version
        g++ -v
        ./mkn -v

    - name: "mkn"
      env:
        MKN_GCC_PREFERRED: 1
        KUL_GIT_CO: --depth 1
      run: |
        KLOG=3 ./mkn clean build run -dtOp test -a "-std=c++17 -fPIC"
